# Generated by Django 3.1.7 on 2021-02-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bg_removal', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bg_removal',
        ),
    ]
