# Generated by Django 3.1.7 on 2021-02-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg_removal', '0003_delete_bg_removal'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/default_image.jpeg', upload_to=''),
        ),
    ]
