# Generated by Django 3.1.7 on 2021-03-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bg_removal', '0004_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
