# Generated by Django 3.1.7 on 2021-03-03 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bg_removal', '0008_auto_20210303_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
