# Generated by Django 3.1.7 on 2021-03-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bg_removal', '0015_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
