# Generated by Django 3.1.7 on 2021-03-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg_removal', '0021_remove_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/default_image.jpg', upload_to=''),
        ),
    ]
