# Generated by Django 3.1.7 on 2021-03-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg_removal', '0023_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identify', models.CharField(default='identify', max_length=20)),
                ('password', models.CharField(default='password', max_length=20)),
            ],
        ),
    ]
