# Generated by Django 3.1.7 on 2021-03-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg_removal', '0024_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='category', max_length=200),
        ),
    ]
